# +--------------------+
# LÓGICA PRINCIPAL
# +--------------------+

name: Security - Docker - Registry Orchestrator
on:
#  schedule: # 


#    - cron: '0 0 * * *'
  push: # 
    branches:
      - main
    paths-ignore: #
      - docker-builder/registry-repos/trivy-tutorial/image_sha.txt

jobs:
  docker-registry-orchestrator:
    name: Docker Registry Orchestrator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current git repo # 
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.trivy}} # 
      - name: Instalar Trivy # 
        run: |
          bash install.sh

      - name: Log in en Dockerhub # 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Interacciones con Docker Registry  # 
        run: |
          bash docker-registry-orchestrator.sh latest ${{ secrets.DOCKERHUB_USERNAME }}
